name: Render Markdown ğŸ“

on:
  push

jobs:
  embed_code:
    name: Open Syncing Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - name: Install gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install
      - run: bundle exec fastlane bootstrap
      - run: bundle exec fastlane open_syncing_pr
