name: Render Markdown üìù

on:
  push:
    branches:
      - test

jobs:
  embed_code:
    name: Open Syncing Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - name: Install gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install
      - run: bundle exec fastlane bootstrap
      - run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
      - run: |
          bundle exec fastlane open_syncing_pr github_pr_token:${{ secrets.PR_TOKEN }} readme_api_key:${{ secrets.README_API_KEY }}
