name: Render Markdown ğŸ“

on:
  push

jobs:
  embed_code:
    name: Embed Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2' # supposedly not needed with a .ruby-version file, but it fails without this Â¯\_(ãƒ„)_/Â¯
          bundler-cache: true
      - run: bundle install
      - run: bundle exec fastlane bootstrap
      - run: bundle exec fastlane render_docs readme_api_key:${{ secrets.README_API_KEY }}
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: "rendered_docs"
