name: Render Markdown ğŸ“

on:
  push

jobs:
  embed_code:
    name: Embed Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 14
      - run: npm install -g embedme
      - run: cp -r docs_source/** rendered_docs/
      - run: embedme "rendered_docs/**/*.md"
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          add: "rendered_docs"